version: "3.7"

services:
  pulumi:
    container_name: local-pulumi
    image: diceytech/pulumi
    command: tail -F anything
    build: .
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - .:/pulumi/projects
    #secrets:
    # - PULUMI_ACCESS_TOKEN
    #  - AWS_ACCESS_KEY_ID
    #  - AWS_SECRET_ACCESS_KEY
    #  - AWS_REGION
